// Copyright (c) 2020 Bitcoin Association
// Distributed under the Open BSV software license, see the accompanying file
// LICENSE.
#pragma once

// Preproccessor definitions to simplify testing

#define SIG 20, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20 

#define SIG_2 SIG, SIG
#define SIG_4 SIG_2, SIG_2
#define SIG_8 SIG_4, SIG_4
#define SIG_16 SIG_8, SIG_8
#define SIG_32 SIG_16, SIG_16

#define SCRIPT_HASH SIG 
#define P2SH_LOCKING OP_HASH160, SCRIPT_HASH, OP_EQUAL

#define MULTISIG_LOCKING_2 OP_1, SIG_2, OP_2, OP_CHECKMULTISIG
#define MULTISIG_LOCKING_4 OP_1, SIG_4, OP_4, OP_CHECKMULTISIG
#define MULTISIG_LOCKING_8 OP_1, SIG_8, OP_8, OP_CHECKMULTISIG
#define MULTISIG_LOCKING_16 OP_1, SIG_16, OP_16, OP_CHECKMULTISIG
#define MULTISIG_LOCKING_32 OP_1, SIG_32, 1, 32, OP_CHECKMULTISIG

#define MULTISIG_LOCKING_20 OP_1, SIG_16, SIG_4, 1, 20, OP_CHECKMULTISIG
#define MULTISIG_LOCKING_21 OP_1, SIG_16, SIG_4, SIG, 1, 21, OP_CHECKMULTISIG

#define MULTISIG_2_IF_LOCKING MULTISIG_LOCKING_2, OP_IF, OP_CHECKSIG, OP_ENDIF 

