# Mandatory settings
excessiveblocksize=0
maxstackmemoryusageconsensus=0
# 1 sat / kb
minminingtxfee=0.00000001

# IBD
blockstallingmindownloadspeed=1000
blockdownloadslowfetchtimeout=15
blockdownloadlowerwindow=250

debug=bench
