# Copyright (c) 2023 Bitcoin Association Distributed under the Open BSV
# software license, see the accompanying file LICENSE

name: 'Functional test'
description:  'Functional test'
inputs:
  tag:
    description: Docker image tag e.g. Ubuntu_22.04
    required: true
  toolset:
    description: Toolset e.g. gcc, clang 
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        ./test/functional/test_runner.py --failfast \
                                         --extended \
                                         --jobs=10 \
                                         --output-type=0 \
                                         --exclude=rpcbind_test # IPv6 not detected reliably
                                                                # on GitHub runners
      shell: bash
    - name: Artifact upload
      if: failure()
      uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7
      with:
        name: ${{ inputs.tag }}-${{ inputs.toolset }}
        path: |
          /tmp/bitcoin_test_runner_*
          !/tmp/bitcoin_test_runner_*/.lock
