// Pipeline for building Bitcoin SV
String cron_string = BRANCH_NAME == "develop" ? "@daily" : ""

pipeline {
    agent { 
        dockerfile  {filename "contrib/nchain/devops/Dockerfile"}
    }

    triggers {
        bitBucketTrigger([[$class: 'BitBucketPPRRepositoryTriggerFilter'
                   , actionFilter: [$class: 'BitBucketPPRRepositoryPushActionFilter'
                   , allowedBranches: '*/develop'
                   , triggerAlsoIfTagPush: false]]
                   , [$class: 'BitBucketPPRPullRequestTriggerFilter'
                   , actionFilter: [$class: 'BitBucketPPRPullRequestApprovedActionFilter'
                   , triggerOnlyIfAllReviewersApproved: false]]])
        cron(cron_string) 
              
    }

    stages {
    
        stage ('Prepare') {
            steps {
                sh 'mv /*.py .'
                sh 'ls -alrt'
		
		slackSend(color:'good',
		    message:"START: Job '${env.JOB_NAME} #${env.BUILD_NUMBER}' (${env.BUILD_URL})")
            }
        }

        stage ('Build') {
            steps {
                bitbucketStatusNotify(buildState: 'BUILDING')
                sh 'python3 entrypoint.py'
            }
        }
 

        stage('Unit Tests') {
            steps {
                bitbucketStatusNotify(buildState: 'UNIT TESTING')
                sh 'python3 pipe-unittests.py'
            }
        }
        stage('secp256k1 Tests') {
            steps {
                bitbucketStatusNotify(buildState: 'EC TESTING')
                sh 'python3 pipe-secp256k1tests.py'
            }
        }
        stage('univalue Tests') {
            steps {
                bitbucketStatusNotify(buildState: 'UNIVALUE TESTING')
                sh 'python3 pipe-univaluetests.py'
            }
        }
        stage('leveldb Tests') {
            steps {
                bitbucketStatusNotify(buildState: 'LEVELDB TESTING')
                sh 'python3 pipe-leveldbtests.py'
            }
        }
        stage('Util Tests') {
            steps {
                bitbucketStatusNotify(buildState: 'UTIL TESTING')
                sh 'python3 pipe-utiltests.py'
            }
        }
        stage('Functional Tests') {
            steps {
                bitbucketStatusNotify(buildState: 'FUNCTIONAL TESTING')
                sh 'python3 pipe-functionaltests.py'
            }
        }

    }
    post {
        cleanup { script:  cleanWs() }
        always  { chuckNorris() }
        success {
            slackSend(color:'good',
                      message:"SUCCESS: Job '${env.JOB_NAME} #${env.BUILD_NUMBER}' (${env.BUILD_URL})")
	    
            bitbucketStatusNotify(buildState: 'SUCCESSFUL')        
            archiveArtifacts 'release-notes.txt \
                             , src/bitcoin-cli \
                             , src/bitcoin-seeder \
                             , src/bitcoin-miner \
                             , src/bitcoin-txt \
                             , src/bitcoind \
                             , build/reports/**'
            junit 'build/reports/*.xml'
        }
        failure {
            bitbucketStatusNotify(buildState: 'FAILED')
	    
            slackSend(color:'danger',
                      message:"FAILURE: Job '${env.JOB_NAME} #${env.BUILD_NUMBER}' (${env.BUILD_URL})")
	    
            script: emailext (
               to: '$DEFAULT_RECIPIENTS',
                subject: "FAILED: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'",
                body: """<p>FAILED: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]':</p>
                <p>Check console output (account needed) at &QUOT; \
                  <a href='${env.BUILD_URL}'>${env.JOB_NAME} [${env.BUILD_NUMBER}]</a>&QUOT;</p>""",
                recipientProviders: [[$class: 'CulpritsRecipientProvider'],
                                     [$class: 'DevelopersRecipientProvider'],
                                     [$class: 'RequesterRecipientProvider'], 
                                     [$class: 'FailingTestSuspectsRecipientProvider'],
                                     [$class: 'FirstFailingBuildSuspectsRecipientProvider'],
                                     [$class: 'UpstreamComitterRecipientProvider']]
            )
        }
        unstable {
	    slackSend(color:'warning',
		message:"UNSTABLE: Job '${env.JOB_NAME} #${env.BUILD_NUMBER}' (${env.BUILD_URL})")
	}
    }
}
