# Copyright (c) 2024 BSV Blockchain Association

name: 'Benchmark test'
description: 'Benchmark test of C.I. environment'
runs:
  using: "composite"
  steps:
    - run: .github/workflows/benchmark/benchmark.sh 
      shell: bash
