# Copyright (c) 2024 BSV Blockchain Association
# Distributed under the Open BSV software license,
# see the accompanying file LICENSE.

name: Fuzz Testing

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  placeholder:
    runs-on: arc-runner-svnode
    container:
      image: nchain/svn_dev:ubuntu_24.04
    steps:
      - name: No-op
        run: echo "Placeholder for fuzz testing"


