# Copyright (c) 2024 BSV Blockchain Association
# Distributed under the Open BSV software license,
# see the accompanying file LICENSE.

name: IBD - Weekend

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  ibd_weekend:
    runs-on: [ self-hosted, docker, large, perf ]
    container:
      image: nchain/svn_dev:ubuntu_22.04
      options: --cap-add SYS_ADMIN --volume /lib/modules:/lib/modules
    strategy:
      max-parallel: 1
      matrix:
        array: [
          { duration: $((5 * 60 * 60)), clean: true },
          { duration: $((5 * 60 * 60)), clean: false },
          { duration: $((5 * 60 * 60)), clean: false },
          { duration: $((5 * 60 * 60)), clean: false },
          { duration: $((5 * 60 * 60)), clean: false },
          { duration: $((5 * 60 * 60)), clean: false },
        ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          clean: ''
      - name: Build Bitcoin
        uses: ./.github/workflows/build_bitcoin_cmake
        with: 
          build_type: Release
      - name: Initial Block Download
        uses: ./.github/workflows/ibd
        with:
          duration: ${{ matrix.array.duration }}
          clean: ${{ matrix.array.clean }}
